image: registry.gitlab.com/libadg/adg:stretch

stages:
    - build
    - test
    - dist

build-autotools-gtk2:
    stage: build
    script:
        - ./autogen.sh
        - mkdir build
        - cd build
        - ../configure --disable-gtk-doc
                       --disable-introspection
                       --disable-pango
                       --with-gtk=gtk2
                       --disable-test-framework
        - make

build-autotools:
    stage: build
    script:
        - ./autogen.sh
        # `autogen.sh` generated files must be shared across stages,
        # so copy everything under `tree/` for future consumption
        - mkdir -p tree/build
        - find . -maxdepth 1 -not -iname '.*' -not -iname 'tree' -exec cp -a {} tree/ '\;'
        - cd tree/build
        - ../configure --enable-gcov
                       --enable-gtk-doc
                       --enable-introspection
                       --enable-pango
                       --with-gtk=gtk3
                       --enable-test-framework
        - make
    artifacts:
        paths:
            - tree/

build-meson-gtk2:
    stage: build
    script:
        - meson -D gtk=gtk2
                -D gtk-doc=disabled
                -D introspection=disabled
                -D pango=disabled
                -D tests=disabled
                build
        - cd build
        - ninja

build-meson:
    stage: build
    script:
        - meson -D b_coverage=true
                -D gtk=gtk3
                -D gtk-doc=enabled
                -D introspection=enabled
                -D pango=enabled
                -D tests=enabled
                build
        - cd build
        - ninja
    artifacts:
        paths:
            - build/

test-autotools:
    stage: test
    needs:
        - build-autotools
    script:
        - cd tree/build
        - make check
    artifacts:
        paths:
            - tree/

test-meson:
    stage: test
    needs:
        - build-meson
    script:
        - cd build
        - ninja test
    artifacts:
        paths:
            - build/

dist-autotools:
    stage: dist
    needs:
        - test-autotools
    script:
        - cd tree/build
        - make distcheck
        - mkdir autotools-dist
        - for f in *.bz2; do sha256sum -b $f > autotools-dist/$f.sha256sum && mv $f autotools-dist/; done
    artifacts:
        expire_in: 1 day
        paths:
            - tree/build/autotools-dist/

dist-meson:
    stage: dist
    needs:
        - test-meson
    script:
        - cd build
        - ninja dist
    artifacts:
        expire_in: 1 day
        paths:
            - build/meson-dist/
