image: registry.gitlab.com/libadg/adg:stretch

stages:
    - build
    - test

build-gtk2-autotools:
    stage: build
    script:
        - ./autogen.sh
        - mkdir build-autotools-gtk2
        - cd build-autotools-gtk2
        - ../configure --enable-gtk-doc --with-gtk=gtk2
        - make

build-gtk3-autotools:
    stage: build
    script:
        - ./autogen.sh
        - mkdir build-autotools-gtk3
        - cd build-autotools-gtk3
        - ../configure --enable-gtk-doc --with-gtk=gtk3
        - make

build-gtk2-meson:
    stage: build
    script:
        - meson -D gtk=gtk2 build-meson-gtk2
        - cd build-meson-gtk2
        - ninja

# Default build target: include everything possible
build-meson:
    stage: build
    script:
        - meson -D b_coverage=true
                -D gtk=gtk3
                -D pango=enabled
                -D gtk-doc=enabled
                -D introspection=enabled
                -D tests=enabled
                build
        - cd build
        - ninja

test-meson:
    stage: test
    needs: [build-meson]
    script:
        - cd build
        - ninja test
