branches:
    only:
        - master

language: c

compiler:
    - clang
    - gcc

env:
    - GTK=gtk2
    - GTK=gtk3

before_install:
    - sudo apt-get update -qq
    - sudo apt-get -y install -t xenial-backports ninja-build

install:
    - sudo apt-get -qq install
      python3 python3-pip python3-setuptools python3-wheel
      libcairo2-dev libcairo-gobject2
      libgtk2.0-dev libgtk-3-dev gtk-doc-tools
    - sudo pip install cpp-coveralls
    - sudo pip3 install 'meson<0.57'

script:
    - meson -Db_coverage=true -Dgtk=$GTK _build &&
      meson compile -C _build &&
      meson test    -C _build

after_success:
    - if [ "$CC" = "gcc" ]; then
      coveralls -x c -e demo -e src/tests -e src/cpml/tests -e src/adg/tests --gcov-options '\-lp';
      fi

notifications:
    email:
        recipients:
            - ntd@entidi.it
