#!/bin/bash
#
# Builds a windows installer on a UNIX system. It depends
# on a lot of stuff such as wine, a proper MinGW toolchain
# and my GTK2/3 cross-compiled environment found at
# http://github.com/ntd/aur-fedora-mingw
#
# It supersedes the old configure scripts still distributed
# (build/configure-win32 and build/configure-win64) by
# properly cross-compiling the ADG project with
# gobject-introspection enabled.
#
# It accepts an optional argument for specifying the target
# architecture. Use "win32" (or omit the argument altogether)
# for a 32 bit build, use "win64" for a 64 bit build.

case "$1" in

"win32" | "")
    arch=i686-w64-mingw32
    ;;

"win64")
    arch=x86_64-w64-mingw32
    ;;

*)
    echo "Invalid argument"
    echo "Usage: $0 [win32|win64]"
    exit 1
    ;;
esac

# This script only works in the root dir or in a VPATH build
# one level under the root dir
if [ -x ./configure ]; then
    tardir=.
elif [ -x ../configure ]; then
    tardir=..
fi

# Step 1: cross-build ADG for $arch
#  Execute the scripts inside a subshell so there will be
#  no visible environment changes from outside.
(
    # The configure scripts provided by the aur-fedora-mingw
    # found at http://github.com/ntd/aur-fedora-mingw are intended to
    # be used from makepkg: let us adapt them for external usage
    CHOST=$($tardir/build/config.guess)
    srcdir="$TMPDIR"
    [ -z "$srcdir" ] && srcdir=/tmp
    srcdir="$srcdir/$(whoami)/adg-wine"
    mkdir -p "$srcdir"

    # Source the wrapper so the environment set by the configure script
    # is retained for the next make call
    MINGW_EXTRA_CFLAGS='-mwindows'
    source /usr/bin/$arch-configure "$tardir" \
	--prefix= \
	--enable-shared \
	--enable-static \
	--enable-pango \
	--disable-gtk-doc \
	--with-gtk=gtk3 \
	--enable-introspection \
	--disable-test-framework \
	"$@"

    make -j
)

# Step 2: create the installer
#   Force empty flags because the cached ones are intended for to be
#   consumed by step 1 (cross-build), not by step 2 (straight build).
make -j installer CPPFLAGS= CFLAGS= LDFLAGS=
